### PR TITLE
fix(lint): Fix all lint errors

### PR DESCRIPTION
**Pull request by jafin**
<strike>This is a stacked PR on top of https://github.com/AxaFrance/oidc-client/pull/1409</strike>
rebased on main

- Fix all eslint errors in codebase.
  - Imports sort and redundency
  - semicolons
  - const vs let
  - Other minor refactors

### CODE REVIEW

**Comment by guillaume-chervet** [comment]
Hi @jafin thank you so much again. I may merge https://github.com/AxaFrance/oidc-client/pull/1402 before. I have to checkout the code but i am in 4 days week-end whithout computer.  I am doing as fast as i can.

**Comment by jafin** [comment]
@guillaume-chervet  yeah no urgency, just thought I'd tidy up the warnings. I know it is quite a wide PR.   If after the #1402 I can rebase this if there are conflicts.

**Comment by guillaume-chervet** [comment]
hi @jafin https://github.com/AxaFrance/oidc-client/pull/1402 has been merged :)

**Comment by jafin** [comment]
@guillaume-chervet , 
rebased and merged changes.  should be good for review.

**Review by guillaume-chervet — APPROVED** [review]
Thank you so much @jafin !

**Pull request merged**
