### PR TITLE
Update FAQ.md

### PR DESCRIPTION
**Pull request by pixellos**
Grammar/style were fixed.

### CODE REVIEW

**Comment by guillaume-chervet** [comment]
Thank you very much @pixellos .
That sounds a lot better

**Review by guillaume-chervet — APPROVED** [review]
Thank you so much @pixellos

**Comment by pixellos** [comment]
Thanks for creating such a wonderful lib - It is the implementation I was dreaming of :)

**Comment by guillaume-chervet** [comment]
Thank you very much @pixellos 😀

**Pull request merged**
