### PR TITLE
feature(tokens): renewtokenswithextras

### PR DESCRIPTION
**Pull request by guillaume-chervet**
#490

### CODE REVIEW

**Comment by 0ctav0** [comment]
Any progress?

**Comment by guillaume-chervet** [comment]
I had a New baby that stop me for that pull request.
Do you need it? May you describz what you need. I am not sure about what i should do.

**Comment by guillaume-chervet** [comment]
Are you using v5? It should refresh the page automaticaly 
 before access token expire. Are you using the service worker?

**Comment by 0ctav0** [comment]
> Are you using v5? It should refresh the page automaticaly before access token expire. Are you using the service worker? Your problem may not be related to this pullrequest.
> 
> Did you request offline_access scope in order to retreive the refresh token?

Yes, I'm using latest v5. No I'm not using service worker and I think neither offline_access (I will check later). The service worker is necessary to auto refresh tokens? Yes it seems it's not related to this pullrequest.

**Comment by guillaume-chervet** [comment]
You need to request offline_access scope. Whithout it you won't retrieve refresh token.

**Comment by 0ctav0** [comment]
> You need to request offline_access scope. Whithout it you won't retrieve refresh token.

It seems working without offline_access scope. It refreshing before token expire. Though I have 2 problems. The first when backend is reloading all tokens expire and this library doesnt know it's need to update. This method renewtokens can help to retrieve token on 401 status code. The second problem is by any reason after some time I get "Session Timed Out" page. Though in dev ok, but in production is not

**Comment by guillaume-chervet** [comment]
Hi @0ctav0, do you have a sample of your access token and idtoken?
Also a sample of your configuration?

I have to use a better algorithme to compute token validity. I will do it in priority.

**Comment by guillaume-chervet** [comment]
Do you know if you retrieve the refresh token?

**Comment by guillaume-chervet** [comment]
I close the pullrequest by error.
Which browser are you using?

**Comment by 0ctav0** [comment]
Sorry for long delay. I use Google Chrome. When I receive data from identity server I get an id_token and an access_token. I dont get a refresh token. As I said before, re-getting access_token works without refresh token. Though after some time I get the Session Time Out page.
I can't send tokens it's secret info. I can send tokens after installation local backend services
Configuration:
`{
  client_id: "my-proj",
  redirect_uri: `${baseUrl}/authentication/callback`,
  silent_redirect_uri: `${baseUrl}/authentication/silent-callback`,
  scope: "openid profile roles",
  authority, // 'https://identity.mydomain.com',
}`

**Comment by guillaume-chervet** [comment]
Hi @0ctav0 , I am not sure i understand your problem. Once accessToken is invalid, react oidc is able to retrieve a new valid accessToken using silent sign. It will work until cookies from your authentication server are valid.

Once everything is invalid the onsessionlost page appear. You can also take the full control of losing the session by using the onsessionlost event it will prevent the default page to appear. It up to you to code the behavior you want.

**Pull request closed without merging**
