### PR TITLE
Tab specific state nonce

### PR DESCRIPTION
**Pull request by meesvandongen**

### CODE REVIEW

**Comment by guillaume-chervet** [comment]
hi @meesvandongen  thank you so mush for your pullrequest. very sorry I did saw it before !

Which PR is the most important to watch first?

**Comment by meesvandongen** [comment]
This one

**Comment by guillaume-chervet** [comment]
Hi @meesvandongen , i did not enough time to clon e it and test it today.
Tomorrow I should have more time. Thank your help i will do my best to be as quicker as possible.

**Comment by meesvandongen** [comment]
Don't worry about it. I am thankful that you will look at it at all. I am still on holiday so I will not be able to make any code changes if it would be necessary on short term.

**Comment by krzempekk** [comment]
Hi @guillaume-chervet! Can this PR be merged?

**Comment by guillaume-chervet** [comment]
Hi @krzempekk it does not work and i am unable to see the changes because of code reformating.

**Comment by krzempekk** [comment]
I have tested it as well and it indeed doesn't work. I will try to investigate and maybe create other PR with fix

**Comment by krzempekk** [comment]
@guillaume-chervet I have opened a new PR for this issue - https://github.com/AxaFrance/oidc-client/pull/1402

**Pull request closed without merging**
